### ISSUE TITLE
Нельзя заполнить ранее судим

### ISSUE THREAD

**Issue by MetalYeti** [andmoni/StatCards#2]
Так и не понял откуда берется значение реквизита 15 - в форме 1.1 редактирование недоступно и написано, что берется из формы 2. В форме 2 редактирование реквизита 45 недоступно и сказано что соответствует р.15 ф.1.1. Так как его заполнить то?

В реквизите 21.1 формы 1 второй разряд слева не проставляется (улица, площади...)

**Comment by andmoni** [comment]
> Еще в форме 3 номер соединенного/выделенного дела короткий, новый 17-значный не написать

Версия с добавлением new не основной проект. В работе использую версию без new, поэтому там меньше всего ошибок. Наш ИЦ принимает последние 6 цифр номера. Для версии c new исправлю карточку в версии 1.007.
